[PHP]
memory_limit = 256M
upload_max_filesize = 20M
post_max_size = 20M
max_execution_time = 60
max_input_time = 60
variables_order = "EGPCS"
expose_php = Off

[Date]
date.timezone = UTC

[Session]
session.gc_maxlifetime = 7200
